version: '3.3'
services:
  db-test:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_ROOT_PASSWORD: 'test'
    ports:
      - '3306:3306'
    expose:
      - '3306'